Fix typing of trigger to include `args`
GrapesJS/grapesjs pull request #4910
Opened 2023-02-06 15:10 UTC by Zaxcoding

Hello, I noticed that the typing for `editor.trigger` did not match betwee [`editor/index.ts`](https://github.com/GrapesJS/grapesjs/blob/a83847b1b35e69e5a5810ccf1eb1e1384bf0aab1/src/editor/index.ts#L761-L769) and the root `index.d.ts`, so I updated the `index.d.ts` to include the `args` param.

2023-02-07 07:37 UTC, artf requested changes
Thanks @Zaxcoding this file is kind of temporary declaration and will be deprecated once we'll release the declaration generated directly from code, but at the moment I accept PRs here anyway.

In your changes you have to rollback `GrapesEvent` as there is no `EditorEvent` in this file.

2023-02-07 14:57 UTC, Zaxcoding commented
Sorry about that, I think `EditorEvent` must have come from the other definition for `trigger`.

2023-02-10 08:11 UTC, artf approved these changes

2023-02-10 08:12 UTC, merged

2023-02-10 08:12 UTC, artf commented
Thank you Zach