Cleanup Component models
GrapesJS/grapesjs pull request #5843
Opened 2024-04-25 12:19 UTC by xQwexx

This pr clean up the component models.

2024-05-28 07:22 UTC, artf commented
Hey @xQwexx sorry my bad I left this PR open for too long, but are you able to fix conflicts first before the review, please?

2024-05-28 08:10 UTC, xQwexx commented
@artf  Np, I updated it 👍

2024-05-28 12:03 UTC, artf requested changes
Nice 👏, commented just one thing

2024-06-03 08:32 UTC, artf approved these changes

2024-06-03 08:32 UTC, merged